function summary=run_predict_microbe_contributions_v3(varargin)
% Continuous 8-worker queue restricted to the verified smallest model's IEX IDs.
cobraRoot='/mnt/nfs/wangchao/softwares/cobratoolbox';
addpath(fullfile(cobraRoot,'src','analysis','multiSpecies','microbiomeModelingToolbox','additionalAnalysis'));
pmcConfigureCobra(cobraRoot,'/home/wangchao/workdir/softwares/cplex/cplex129/CPLEX_Studio');
base='/mnt/nfs/wangchao/my_course/untreated_MS/replace_data/step4_modeling/predict_microbe_contributions';
x=load(fullfile(base,'reference_targets_20260915.mat'),'reference');
assert(~isempty(x.reference.targetRxns),'Reference target list is empty.');
fprintf('Reference %s: %d reactions, %d coupling rows, %d IEX target IDs.\n', ...
    x.reference.name,x.reference.reactions,x.reference.couplingRows,x.reference.targetCount);
[~,~,~,summary]=predictMicrobeContributions(fullfile(base,'run_20260507_204155','ordered_models'), ...
    'resultsFolder',fullfile(base,'run_reference_rolling_20260915'), ...
    'cacheFolder',fullfile(base,'lean_model_cache_v1'), ...
    'scheduling','rolling','numWorkers',8,'failOnError',false,'returnTables',false, ...
    'targetRxns',x.reference.targetRxns,'reactionChunkSize',1000,'numericalRetry',true, ...
    'priorResultsFolder',fullfile(base,'run_refactored_8'),varargin{:});
end
