function build_pmc_backend(cplexRoot)
% Build a separate binary; never overwrite COBRA's existing cplexFVA binaries.
if nargin==0,cplexRoot='/home/wangchao/workdir/softwares/cplex/cplex129/CPLEX_Studio';end
here=fileparts(mfilename('fullpath'));
mex('-largeArrayDims','-DHIGHER_THAN_128', ...
    ['-I' fullfile(cplexRoot,'cplex','include','ilcplex')], ...
    fullfile(here,'pmcCplexFVA.c'), ...
    fullfile(cplexRoot,'cplex','lib','x86-64_linux','static_pic','libcplex.a'), ...
    '-lpthread','-ldl','-lm','-outdir',here,'-output','pmcCplexFVA');
end
